# Generated by Django 5.1 on 2024-08-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('org_url', models.URLField()),
                ('no_clicks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
