# Generated by Django 5.1 on 2024-08-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='org_url',
            new_name='orgurl',
        ),
    ]
